[cv]
cv_compile_base_dir = "/opt/data/cv/output"
# cv_api_url = "http://10.98.93.22:11015"
x_access_token = ""
cv_api_url = "http://127.0.0.1:8000"
compile_group_name = "g-comp-queue"
compile_stream_redis_key = "texhub-server:proj:s-comp-queue"
texhub_api_url = "http://tex-service.reddwarf-pro.svc.cluster.local:8000"