apiVersion: v1
kind: Service
metadata:
  name: cv-render-service
  namespace: reddwarf-pro
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: cv-render-service
  clusterIP: 10.109.86.113
  clusterIPs:
    - 10.109.86.113
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
