name: cv-render-pro

on:
  push:
    branches: [ main-legacy ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release && chmod +x target/release/cv-render
  
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: "target/release/cv-render,settings-production.toml,script/startup-production.sh"
          target: /home/ubuntu/apps/cv-render/

      - name: Restart app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            export ENV=TENCENT
            cd /home/ubuntu/apps/cv-render
            mv /home/ubuntu/apps/cv-render/settings-production.toml /home/ubuntu/apps/cv-render/settings.toml
            nohup /home/ubuntu/apps/cv-render/script/startup-production.sh > /home/ubuntu/apps/cv-render/startup.log 2>&1 &!
            sleep 15
